---
title: "Gov 50 Final Project"
author: "Ella Trembanis"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Introduction



## Data

```{r setup}
library(tidyverse)
library(ggplot2)

# loading the dataset

euro <- read.csv("2022_jury_results.csv")

# creating a new variable

euro <- euro |>
  mutate(
    big_five = if_else(Contestant == "France" | 
                         Contestant == "Germany" |
                         Contestant == "Italy" | 
                         Contestant == "Spain" |
                         Contestant == "United Kingdom", 
                       "Big Five", "Not Big Five")
  )
```

```{r dependent var visualization}
top_scores <- euro |>
  group_by(Contestant, big_five) |>
  summarize(
    score = mean(Total.score, na.rm = TRUE)
  )

ggplot(top_scores, mapping = aes(x = score, y = fct_reorder(Contestant, score))) +
  geom_col() +
  labs(
    title = "Distribution of 2022 Eurovision Final Scores",
    x = "Total Score",
    y = "Contestant"
  )
```

## Results

```{r barplot visualization}
# creating a barplot visualization

euro_bar <- euro |>
  group_by(big_five) |>
  summarize(
    avg_score = mean(Total.score, na.rm = TRUE)
  ) |>
  ggplot(mapping = aes(x = big_five, y = avg_score, fill = big_five)) +
  geom_col() +
  labs(
    title = "Average 2022 Eurovision Scores for Big Five and Non-Big Five Countries",
    x = "Big Five Status",
    y = "Average Total Score in 2022"
  ) +
  theme(legend.position = "none")

euro_bar
```

```{r single linear regression}
# creating a linear regression for the main variable

fit1 <- lm(Total.score ~ big_five, data = euro)

library(modelsummary)

var_labels <- c(
  "(Intercept)" = "Intercept",
  "big_fiveNot Big Five" = "Not Big Five"
)

modelsummary(list(Regression = fit1),
             statistic = "p.value",
             fmt = fmt_decimal(digits = 2, pdigits = 3),
             coef_map = var_labels,
             gof_map = c("nobs", "r.squared", "adj.r.squared"))
```

```{r joining a dataset}
# loading a new dataset

song <- read.csv("song_data.csv")

song <- song |>
  filter(year == 2022, final_draw_position != "-") |>
  rename(Contestant = country) |>
  mutate(
    english = if_else(language == "English", "English", "Other"),
    dancers = if_else(backing_dancers > 0, "Backing Dancers", "No Backing Dancers"),
    singers = if_else(main_singers > 1, "Multiple Singers", "One Singer")
  )

# joining euro and song

euro_song <- left_join(euro, song, by = 'Contestant') |>
  select(Contestant, Total.score, Jury.score, Televoting.score, big_five, 
         final_draw_position, language, style, gender, main_singers, key, 
         BPM, energy, danceability, happiness, loudness, acousticness, 
         instrumentalness, liveness, speechiness, dancers, english,
         singers, backing_instruments, instrument_10, race)
```

```{r multiple regression}
# creating a multiple regression

fit2 <- lm(Total.score ~ big_five + gender + dancers + singers + english, data = euro_song)

var_labels <- c(
  "(Intercept)" = "Intercept",
  "big_fiveNot Big Five" = "Not Big Five",
  "genderMale" = "Male",
  "genderMix" = "Mixed Gender",
  "dancersNo Backing Dancers" = "No Backing Dancers",
  "singersOne Singer" = "One Singer",
  "englishOther" = "Non-English Lyrics"
)

modelsummary(list(Regression = fit2),
             statistic = "p.value",
             fmt = fmt_decimal(digits = 2, pdigits = 3),
             coef_map = var_labels,
             gof_map = c("nobs", "r.squared", "adj.r.squared"))
```


## Conclusion